apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: promoter-system

resources:
  - gitrepository.yaml
  - argocdcommitstatus.yaml
  - promotionstrategy.yaml
  - scmprovider.yaml
  - webrequestcommitstatus.yaml
