apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitrepository.yaml
  - argocdcommitstatus.yaml
  - promotionstrategy.yaml
  - scmprovider.yaml
  - webrequestcommitstatus.yaml
