{
 "title": "Strimzi Kafka OAuth",
 "tags": [
  "Strimzi",
  "Kafka",
  "OAuth"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(strimzi_oauth_http_requests_count_total)"
   }
  ]
 },
 "panels": [
  { "title": "OAuth Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OAuth HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(strimzi_oauth_http_requests_count_total{namespace=\"$kubernetes_namespace\"}[$__rate_interval]) * 30",
     "legendFormat": "[{{context}}] (Status: {{status}})"
    }
   ]
  },
  {
   "title": "OAuth Validation Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "irate(strimzi_oauth_validation_requests_count_total{namespace=\"$kubernetes_namespace\"}[$__rate_interval]) * 30",
     "legendFormat": "[{{context}}] (Outcome: {{outcome}})"
    }
   ]
  },
  {
   "title": "OAuth HTTP Request Avg Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "strimzi_oauth_http_requests_avgtimems{namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "[{{context}}] (Status: {{status}})"
    }
   ]
  },
  {
   "title": "OAuth Validation Avg Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "strimzi_oauth_validation_requests_avgtimems{namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "[{{context}}] (Outcome: {{outcome}})"
    }
   ]
  },
  {
   "title": "OAuth HTTP Total Time / Request (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "strimzi_oauth_http_requests_totaltimems_total{namespace=\"$kubernetes_namespace\"} / strimzi_oauth_http_requests_count_total{namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "[{{context}}] (Status: {{status}})"
    }
   ]
  },
  {
   "title": "OAuth Validation Total Time / Request (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "strimzi_oauth_validation_requests_totaltimems_total{namespace=\"$kubernetes_namespace\"} / strimzi_oauth_validation_requests_count_total{namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "[{{context}}] (Outcome: {{outcome}})"
    }
   ]
  }
 ]
}