apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: my-cluster-controller
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 1Gi
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: my-cluster-broker
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 1Gi
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
    showAllOffsets: false
    logging: info
    enableSaramaLogging: false
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  kafka:
    version: 4.0.0
    metadataVersion: "4.0"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: custom
          sasl: true
          listenerConfig:
            sasl.enabled.mechanisms: OAUTHBEARER
            oauthbearer.sasl.server.callback.handler.class: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
            oauthbearer.sasl.jaas.config: >
              org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required unsecuredLoginStringClaim_sub="thePrincipalName"
              oauth.valid.issuer.uri="http://sso.local.io:32080/realms/kafka-authz"
              oauth.jwks.endpoint.uri="http://sso.local.io:32080/realms/kafka-authz/protocol/openid-connect/certs"
              oauth.username.claim="preferred_username"
              oauth.enable.metrics="true";
            connections.max.reauth.ms: 3600
    authorization:
      type: custom
      authorizerClass: io.strimzi.kafka.oauth.server.authorizer.KeycloakAuthorizer
      superUsers:
        - service-account-kafka
        - service-account-kafka-bridge
        - service-account-kafka-connect
    config:
      initial.broker.registration.timeout.ms: 300000 # 5min
      broker.heartbeat.interval.ms: 2000
      auto.create.topics.enable: "true"
      # Needed for Oauth authentication and Keycloak authroization
      principal.builder.class: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
      # Needed for Keycloak authorization
      strimzi.authorization.client.id: kafka
      strimzi.authorization.token.endpoint.uri: http://sso.local.io:32080/realms/kafka-authz/protocol/openid-connect/token
      strimzi.authorization.ssl.endpoint.identification.algorithm: ""
      strimzi.authorization.delegate.to.kafka.acl: "true"
      # Other Kafka configuration options
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      jvmOptions: "-Xms512M -Xmx1024M"
    template:
      kafkaContainer:
        env:
          # - name: OAUTH_ENABLE_METRICS
          #  value: "true"
          - name: STRIMZI_OAUTH_METRIC_REPORTERS
            value: org.apache.kafka.common.metrics.JmxReporter
    logging:
      type: inline
      loggers:
        log4j.logger.io.strimzi: "INFO"
        log4j.logger.kafka: "INFO"
        log4j.logger.org.apache.kafka: "INFO"
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yaml
  entityOperator:
    topicOperator: {}
    userOperator: {}
