---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: x-topic
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: x_topic
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: a-topic
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: a_topic
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: b-topic
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: b_topic
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
---
