apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-kafka-reader
  namespace: kafka-cluster-2
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cluster-2-secret-store
  namespace: kafka-cluster-2
spec:
  provider:
    kubernetes:
      remoteNamespace: kafka-cluster
      auth:
        serviceAccount:
          name: eso-kafka-reader
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-2-external-secret
  namespace: kafka-cluster-2
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-2-secret-store
    kind: SecretStore
  target:
    name: cluster-1-mm2-creds
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cluster-1-user-mm2
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-1-external-secret
  namespace: kafka-cluster-2
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-2-secret-store
    kind: SecretStore
  target:
    name: cluster-1-mm2-creds
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cluster-1-user-mm2
        property: password
---
# apiVersion: external-secrets.io/v1
# kind: SecretStore
# metadata:
#   name: cluster-2-secret-store
#   namespace: kafka-ui
# spec:
#   provider:
#     kubernetes:
#       remoteNamespace: kafka-cluster-2
#       auth:
#         serviceAccount:
#           name: eso-kafka-reader
#       server:
#         caProvider:
#           type: ConfigMap
#           name: kube-root-ca.crt
#           key: ca.crt
# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: cluster-2-external-secret
#   namespace: kafka-ui
# spec:
#   refreshInterval: 1m
#   secretStoreRef:
#     name: cluster-2-secret-store
#     kind: SecretStore
#   target:
#     name: ui-kafka-cluster-2-creds
#     creationPolicy: Owner
#   data:
#     - secretKey: password
#       remoteRef:
#         key: kafka-ui
#         property: password