apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules-postgres
  namespace: loki
  labels:
    loki-rules: "true"
data:
  pgsql-alerts.yaml: |
    groups:
      - name: pgsql-fatal-alerts
        interval: 1m
        rules:
          - alert: PostgreSQLFatal
            expr: |
              sum by (k8s_namespace_name) (count_over_time({k8s_namespace_name="grafana-pg", k8s_container_name="postgres"} |= "FATAL" [5m])) > 0
            for: 0m
            labels:
              severity: critical
              team: dba
            annotations:
              summary: "PostgreSQL FATAL error detected"
              description: "FATAL in {{ $labels.k8s_namespace_name }}"
