apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-monitoring
  namespace: loki
  labels:
    release: monitoring
spec:
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
      - loki
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
