apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak-pg
type: Opaque
data:
  username: a2V5Y2xvYWtfYWRtaW4=   # Base64-encoded 'keycloak_admin'
  password: YWRtaW4xMjM=           # Base64-encoded 'admin123'
