apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-kafka-reader
  namespace: default
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kafka-cluster-store
  namespace: default
spec:
  provider:
    kubernetes:
      remoteNamespace: kafka-cluster
      auth:
        serviceAccount:
          name: eso-kafka-reader
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: a-user-kafka-creds
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kafka-cluster-store
    kind: SecretStore
  target:
    name: a-user-kafka-creds
    creationPolicy: Owner
  data:
    - secretKey: sasl.jaas.config
      remoteRef:
        key: a-user
        property: sasl.jaas.config
    - secretKey: password
      remoteRef:
        key: a-user
        property: password
