# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.33.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 32080
        protocol: TCP
      - containerPort: 443
        hostPort: 32443
        protocol: TCP
  - role: worker
    image: kindest/node:v1.33.0
  - role: worker
    image: kindest/node:v1.33.0
  - role: worker
    image: kindest/node:v1.33.0
