---
apiVersion: v1
kind: Namespace
metadata:
  name: app-pg
---
apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: app-pg
type: Opaque
stringData:
  username: app_admin
  password: admin123
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-db
  namespace: app-pg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  bootstrap:
    initdb:
      database: app_db
      owner: app_admin
      secret:
        name: app-db-secret
      postInitSQL:
        - "ALTER ROLE app_admin WITH REPLICATION;"
  storage:
    storageClass: standard
    size: 1Gi
  postgresql:
    parameters:
      wal_level: "logical"
