---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-db
  namespace: app-pg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: app_db
      owner: app_admin
      secret:
        name: app-db-secret
  storage:
    storageClass: standard
    size: 1Gi