crds:
  install: true
  keep: false

controller:
  enabled: true
  workflowNamespaces:
    - default
  metrics:
    enabled: true
  serviceAccount:
    create: true
    name: argo-workflows-controller
  metricsConfig:
    enabled: true
  podAnnotations:
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9090'
    prometheus.io/scrape: 'true'

metrics:
  enabled: true

workflow:
  serviceAccount:
    create: true
    name: argo-workflow
    annotations:
      workflows.argoproj.io/rbac-rule: "'argo-workflows-admin' in groups"
      workflows.argoproj.io/rbac-rule-precedence: "1"
  rbac:
    create: true
    serviceAccounts:
      - name: argo-workflow
        namespace: default
    # rules:
    #   - apiGroups: ["*"]
    #     resources: ["workflows", "workflowtemplates", "cronworkflows", "clusterworkflowtemplates"]
    #     verbs: ["*"]

server:
  enabled: true
  logging:
    level: info
  authModes:
    - sso
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - jobs.local.io
    pathType: Prefix
    paths:
      - /
  extraEnv:
    - name: SSO_DELEGATE_RBAC_TO_NAMESPACE
      value: "true"
  sso:
    enabled: true
    issuer: https://keycloak.local.io:32443/realms/master
    clientId:
      name: argo-workflows-sso
      key: client-id
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    redirectUrl: http://jobs.local.io:32080/oauth2/callback
    scopes:
      - email
      - profile
      - groups
    insecureSkipVerify: true
    rbac:
      enabled: true
      # policy: |
      #   p, role:admin, *, *, */*, allow
      #   g, argo-workflows-admin, role:admin
      # groups.claim: groups
      # policy.default: role:readonly
