controller:
  replicas: 1
  metrics:
    enabled: true

dashboard:
  enabled: true
  service:
    type: ClusterIP
  
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      # nginx.ingress.kubernetes.io/configuration-snippet: |
      #   proxy_set_header Host $host;
      #   proxy_set_header X-Real-IP $remote_addr;
      #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      #   proxy_set_header X-Forwarded-Proto $scheme;
      # nginx.ingress.kubernetes.io/auth-snippet: |
      #   if ($request_uri ~* "^/favicon\.ico$") {
      #     auth_request off;
      #   }
      nginx.ingress.kubernetes.io/server-snippets: |
        location = /favicon.ico {
          access_log off;
          log_not_found off;
          try_files /favicon.ico =204;
        } 
      #nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
      nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "16k"
      #nginx.ingress.kubernetes.io/auth-url: "http://auth.local.io:32080/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-url: "http://oauth2-oauth2-proxy.oauth2.svc.cluster.local/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: http://auth.local.io:32080/oauth2/start
      #nginx.ingress.kubernetes.io/auth-signin: "http://auth.local.io:32080/oauth2/start?rd=https://$host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
    hosts:
      - rollouts.local.io
    paths:
      - /
    pathType: Prefix
