# Admin role SA, Secret and ClusterRole and ClusterRoleBinding
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-token
  annotations:
    kubernetes.io/service-account.name: admin-user
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  annotations:
    workflows.argoproj.io/rbac-rule: "'devops' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "999"
    workflows.argoproj.io/service-account-token.name: admin-user-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-admins
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin    # This role is already defined in kind cluster
---
# Default Role SA, Secret, and its Role and RoleBinding.
# If a user does not belong to any Group by Keycloak then this role permissions will be assigned to the user.
# This has limited permissions.
---
apiVersion: v1
kind: Secret
metadata:
  name: user-default-login-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: user-default-login
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-default-login
  namespace: argo-workflows
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
    workflows.argoproj.io/service-account-token.name: user-default-login-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-user-login-role
  namespace: argo-workflows
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - 'argoproj.io'
    resources:
      - workflows
      - workflowtaskresults
      - workflowtasksets
      - workflowtemplates
      - cronworkflows
      - pods
      - pods/log
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-user-login-rolebinding
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: user-default-login
    namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 
  namespace: 
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - 'argoproj.io'
    resources:
      - workflows
      - workflowtemplates
      - workflowtaskresults
      - workflowtasksets
      - cronworkflows
      - pods
      - pods/log
  - verbs:
      - create
      - patch
      - update
    apiGroups:
      - 'argoproj.io'
    resources:
      - workflows
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
---
# Eng Role SA, Secret, and its Role and RoleBinding.
---
apiVersion: v1
kind: Secret
metadata:
  name: eng-team-token
  namespace: welcome-app
  annotations:
    kubernetes.io/service-account.name: eng-team-sa
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eng-team-sa
  namespace: welcome-app
  annotations:
    workflows.argoproj.io/rbac-rule: "'engineering' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
    workflows.argoproj.io/service-account-token.name: eng-team-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eng-team-clusterrole
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - 'argoproj.io'
    resources:
      - ''
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eng-team-rolebinding
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: eng-team-sa
    namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eng-user-clusterrole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-cluster-role
rules:
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - ''
      - apps
    resources:
      - pods
      - pods/exec
      - secrets
      - deployments
  - verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - create
      - update
      - delete
      - get
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
      - persistentvolumeclaims/finalizers
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - create
    apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workflowtasksets
      - workflowtasksets/finalizers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtemplates
      - workflowtemplates/finalizers
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
  - verbs:
      - list
      - watch
      - create
      - patch
      - deletecollection
    apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - argoproj.io
    resources:
      - cronworkflows
      - cronworkflows/finalizers
  - verbs:
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - create
      - get
      - delete
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: argo-workflows
    namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflow-cluster-role
