apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        hosts {
          172.18.0.2 welcome.local.io sso.local.io secrets.local.io cd.local.io metrics.local.io logs.local.io dashboards.local.io auth.local.io rollouts.local.io idp.local.io traces.local.io jobs.local.io storage.local.io console.storage.local.io app.local.io appdb.local.io kafka-ui.local.io
          172.18.0.3 welcome.local.io sso.local.io secrets.local.io cd.local.io metrics.local.io logs.local.io dashboards.local.io auth.local.io rollouts.local.io idp.local.io traces.local.io jobs.local.io storage.local.io console.storage.local.io app.local.io appdb.local.io kafka-ui.local.io
          172.18.0.4 welcome.local.io sso.local.io secrets.local.io cd.local.io metrics.local.io logs.local.io dashboards.local.io auth.local.io rollouts.local.io idp.local.io traces.local.io jobs.local.io storage.local.io console.storage.local.io app.local.io appdb.local.io kafka-ui.local.io
          172.18.0.5 welcome.local.io sso.local.io secrets.local.io cd.local.io metrics.local.io logs.local.io dashboards.local.io auth.local.io rollouts.local.io idp.local.io traces.local.io jobs.local.io storage.local.io console.storage.local.io app.local.io appdb.local.io kafka-ui.local.io
          fallthrough
        }
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
