adminUser: admin
adminPassword: admin123

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - grafana.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.prometheus.svc.cluster.local
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    flask-app:
      gnetId: 11074  # Example dashboard ID for a Python app
      revision: 1
      datasource: Prometheus
