apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-db
  namespace: grafana-pg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: grafana_db
      owner: grafana_admin
      secret:
        name: grafana-db-secret
      postInitSQL:
        - GRANT USAGE, CREATE ON SCHEMA public TO grafana_admin;
        - ALTER USER grafana_admin CREATEDB;
  storage:
    storageClass: standard
    size: 1Gi