---
# Install Reloader
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: default
  destination:
    namespace: reloader
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://stakater.github.io/stakater-charts'
      chart: reloader
      targetRevision: 2.1.3
  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Install Flask APP
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: app
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/sahil-sharma/k8s-stuff'
      path: flask-otel-app-chart
      targetRevision: main
  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true