apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  host: "*.local.io"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
