production: true

auth:
  adminUser: admin
  adminPassword: admin123

postgresql:
  enabled: false

externalDatabase:
  host: postgres-postgresql.postgres
  port: 5432
  user: keycloak_admin
  password: hello123
  database: keycloak_db

rbac:
  create: true
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list

proxy: edge

extraEnvVars:
  - name: KC_HOSTNAME
    value: "https://login.local.io:32443"
  - name: KC_PROXY_HEADERS
    value: "xforwarded"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME_DEBUG
    value: "true"
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.awt.headless=true
      -Djgroups.dns.query=keycloak-headless

service:
  http:
    enabled: true

metrics:
  enabled: true

startupProbe:
  enabled: false
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: login.local.io
  tls: true
  selfSigned: true
  extraTls:
    - hosts:
        - login.local.io
      secretName: login.local.io-tls
  rules:
  - host: login.local.io
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: keycloak
            port:
              name: http