auth:
  rootPassword: rootpassword
  username: admin
  password: admin123
  database: dummy_db

primary:
  persistence:
    enabled: false

initdbScripts:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS keycloak_db;
    CREATE USER IF NOT EXISTS 'keycloak_admin'@'%' IDENTIFIED BY 'hello123';
    GRANT ALL PRIVILEGES ON keycloak_db.* TO 'keycloak_admin'@'%';
    FLUSH PRIVILEGES;
