auth:
  rootPassword: rootpassword
  username: keycloak_admin
  password: hello123
  database: keycloak_db

primary:
  persistence:
    enabled: false

# initdbScripts:
#   init.sql: |
#     CREATE DATABASE IF NOT EXISTS keycloak_db;
#     CREATE USER IF NOT EXISTS 'keycloak_admin'@'%' IDENTIFIED BY 'hello123';
#     GRANT ALL PRIVILEGES ON keycloak_db.* TO 'keycloak_admin'@'%';
#     FLUSH PRIVILEGES;
