auth:
  username: keycloak
  password: keycloakpassword
  database: keycloakdb

primary:
  persistence:
    enabled: false  # Use emptyDir for Kind (no dynamic PVs by default)
  service:
    type: ClusterIP                   # Internal service for NGINX TCP mapping
    port: 5432
