alertmanager:
  enabled: true
  service:
    type: ClusterIP
  persistentVolume:
    enabled: false

nodeExporter:
  enabled: true
  service:
    type: ClusterIP

pushgateway:
  enabled: false

server:
  persistentVolume:
    enabled: false
  service:
    type: ClusterIP
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 200m
  ingress:
    enabled: false
    hosts:
      - prometheus.local

# Scrape configs can be added to target your Flask app
additionalScrapeConfigs:
  - job_name: 'python3-debian'
    static_configs:
       - targets: ['python3-debian.default.svc.cluster.local:8000']
