alertmanager:
  enabled: false
  service:
    type: ClusterIP
  persistentVolume:
    enabled: false

nodeExporter:
  enabled: true
  service:
    type: ClusterIP

pushgateway:
  enabled: false

server:
  persistentVolume:
    enabled: false
  service:
    type: ClusterIP
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 200m
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - prometheus.local.io
    pathType: Prefix
    paths:
      - /
    tls: []

# Scrape configs can be added to target your Apps
scrape_configs:
  - job_name: 'keycloak'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['keycloak-metrics.keycloak:9000']

# Scrape configs can be added to target your Flask app
# additionalScrapeConfigs:
#   - job_name: 'python3-debian'
#     static_configs:
#        - targets: ['python3-debian.default.svc.cluster.local:8000']
