podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "http-metrics"

config:
  clients:
    - url: https://logs.local.io:32443/loki/api/v1/push
      # tenant_id: "demo-app"  # 👈 if multi-tenancy is enabled
      # Optional basic auth config if enabled:
      #basic_auth:
        #username: root-user
        #password: supersecretpassword

  positions:
    filename: /run/promtail/positions.yaml

  server:
    disable: false
    http_listen_port: 9080
    grpc_listen_port: 0

  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container_name
        - action: replace
          source_labels: [__meta_kubernetes_pod_uid]
          target_label: __path__
          replacement: /var/log/pods/*$1/*.log
          regex: (.*)
