fullnameOverride: sealed-secrets-controller

rbac:
  create: true

serviceAccount:
  create: true
  name: sealed-secrets-controller

networkPolicy:
  enabled: true

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

metrics:
  enabled: true

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: sealed-secrets.local.io
