apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ include "flask-crud-app.name" . }}
data:
  pg_host: {{ .Values.config.pg_host | quote }}
  pg_port: {{ .Values.config.pg_port | quote }}
  pg_db: {{ .Values.config.pg_db | quote }}
  pg_username: {{ .Values.config.pg_username | quote }}
