apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ include "flask-crud-app.name" . }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc }}
