apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ include "flask-crud-app.name" . }}
type: Opaque
data:
  flaskSecretKey: {{ .Values.secret.flaskSecretKey | b64enc }}
