apiVersion: v1
kind: Secret
metadata:
  name: kafka-app-secrets
  namespace: default
type: Opaque
stringData:
  TEAM_A_CLIENT_SECRET: "eJ2Nu5hgZMJKBHrTIlJGiZ1Jn0SzzU6f"
  TEAM_B_CLIENT_SECRET: "4aPcR20xYa4CbwSpzxnJHjvy08MV4hoj"
