apiVersion: v1
kind: Secret
metadata:
  name: kafka-app-secrets
  namespace: default
type: Opaque
stringData:
  TEAM_A_CLIENT_SECRET: "VtJT05IVDTeSNqVeKRTJSmNvx5FN3bvr"
  TEAM_B_CLIENT_SECRET: "mKqFtl29mc5KNb7Aq4jmmWQpWhyF4wAU"
