apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster.yaml
  - topic.yaml
  - kafka-user.yaml
  - metrics-configmap.yaml
  - metrics-service.yaml
  - peer-authentication.yaml
  - virtualservice.yaml
  - cluster-operator-pod-monitor.yaml
  - entity-operator-pod-monitor.yaml
  - kafka-resources-pod-monitor.yaml
  - prometheus-cluster-rule.yaml
  - prometheus-cluster-operator-rule.yaml
  - prometheus-cluster-entity-operator-rule.yaml
  - prometheus-topic-operator-rule.yaml
  - kafka-user-for-kafka-ui.yaml
  - role-and-rolebinding-for-external-secrets.yaml
  # Install Kakfa UI to visualize the cluster and manage topics and users
  - kafka-ui/
