replicaCount: 1

image:
  repository: bonyscott/flask-otel-app
  tag: 6b1e8c3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: app.local.io
      paths:
        - path: /
          pathType: Prefix
        - path: /signup
          pathType: Prefix
        - path: /login
          pathType: Prefix
        - path: /items
          pathType: Prefix
        - path: /external
          pathType: Prefix
  tls: []

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  path: "/healthz"
  port: 5000

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  path: "/healthz"
  port: 5000

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: false
  minAvailable: 1

config:
  DB_HOST: "postgres-postgresql.postgres"
  DB_PORT: 5432
  DB_NAME: "app_db"
  DB_USER: "app_admin"
  TRACING_ENABLED: "false"  # or "true"
  OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector.otel:4318/v1/traces"

secrets:
  JWT_SECRET: "jwtsecretkey"
  DB_PASSWORD: "hello123"

serviceAccount:
  create: true

nodeSelector: {}

tolerations: []

affinity: {}
