replicaCount: 1

image:
  repository: bonyscott/flask-otel-app
  tag: 5197625
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: flask.local
      paths:
        - path: /
          pathType: Prefix
        - path: /signup
          pathType: Prefix
        - path: /login
          pathType: Prefix
        - path: /items
          pathType: Prefix
        - path: /external
          pathType: Prefix
  tls: []

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  path: "/healthz"
  port: 5000

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  path: "/healthz"
  port: 5000

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: false
  minAvailable: 1

config:
  DB_HOST: postgres-postgresql.postgres
  DB_PORT: 5432
  DB_NAME: flaskdb
  DB_USER: flaskuser
  OTLP_ENDPOINT: http://open-telemetry-opentelemetry-collector.otel-collector:4318/v1/traces

secrets:
  JWT_SECRET: jwtsecretkey
  DB_PASSWORD: flaskpassword

serviceAccount:
  create: true

nodeSelector: {}

tolerations: []

affinity: {}
