replicaCount: 2

image:
  repository: bonyscott/flask-otel-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: flask.local
      paths:
        - path: /
          pathType: Prefix
        - path: /signup
          pathType: Prefix
        - path: /login
          pathType: Prefix
        - path: /items
          pathType: Prefix
        - path: /external
          pathType: Prefix
  tls: []

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  path: "/"
  port: 5000

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  path: "/"
  port: 5000

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 1

config:
  environment: development

secret:
  flaskSecretKey: your-super-secret-key

serviceAccount:
  create: true

nodeSelector: {}

tolerations: []

affinity: {}
