kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

grafana:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    secrets:
      - slack-webhook-secret
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname", "namespace", "topic"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "slack"
      routes:
        - receiver: "null"
          matchers:
            - alertname =~ "Watchdog|InfoInhibitor"
    receivers:
      - name: "null"
      - name: "slack"
        slack_configs:
          - channel: "#platform-alerts"
            api_url_file: "/etc/alertmanager/secrets/slack-webhook-secret/slack-webhook-url"
            title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonAnnotations.summary }}'
            text: >-
              {{ range .Alerts -}}
              *Alert:* `{{ .Labels.alertname }}`
              *Severity:* `{{ .Labels.severity | toUpper }}`
              *Description:* {{ .Annotations.description }}{{ if .Labels.namespace }}
              *Namespace:* {{ .Labels.namespace }}{{ end }}
              {{- end }}
            color: >-
              {{ if eq .Status "firing" -}}
                {{- $severity := "warning" -}}
                {{- range .Alerts -}}
                  {{- if eq .Labels.severity "critical" -}}
                    {{- $severity = "critical" -}}
                  {{- end -}}
                {{- end -}}
                {{- if eq $severity "critical" -}} #FF0000 {{- else -}} warning {{- end -}}
              {{- else -}}
                good
              {{- end }}

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    # Discovery: Pick up every ServiceMonitor/Rule in the cluster
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 1d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "standard"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
