---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-root-login-sa
  namespace: minio
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: minio-root-secret-store
  namespace: minio
spec:
  provider:
    vault:
      server: "http://secrets.local.io:32080"
      path: "apps"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "minio-root-secret-role"
          serviceAccountRef:
            name: minio-root-login-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-external-secret
  namespace: minio
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: minio-root-secret-store
    kind: SecretStore
  target:
    name: minio-root-credentials
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio
        property: MINIO_ROOT_USER
    - secretKey: rootPassword
      remoteRef:
        key: minio
        property: MINIO_ROOT_PASSWORD
