apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: keycloak
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - sso.local.io
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: keycloak-db-gateway
  namespace: keycloak-pg
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 5432
      name: tcp-postgres
      protocol: TCP
    hosts:
    - "*"
---