apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: kafka-dashboards
    files:
      - strimzi-kafka-metrics.json
      - strimzi-kafka-exporter-metrics.json
  - name: kafka-addons-dashboards
    files:
      - strimzi-kafka-bridge-metrics.json
      - strimzi-kafka-connect-metrics.json
      - strimzi-kafka-oauth-metrics.json

resources:
  - namespace.yaml
  - gateway.yaml
  - virtualservice.yaml
  - peer-authentication.yaml
  - secret.yaml # Deploy this if not using SSO and want to use basic auth with Grafana
# - grafana-external-secret.yaml # Deploy this if you want to use External Secrets to manage Grafana credentials

helmCharts:
  - name: grafana
    releaseName: grafana
    namespace: grafana
    repo: https://grafana-community.github.io/helm-charts
    version: 11.1.7
    valuesFile: values.yaml
