apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-secret
  namespace: grafana-pg
type: Opaque
data:
  # Encoded using: echo -n "grafana_admin" | base64
  username: Z3JhZmFuYV9hZG1pbg==  
  # Encoded using: echo -n "admin123" | base64
  password: YWRtaW4xMjM=
