---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-db
  namespace: grafana-pg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  bootstrap:
    initdb:
      database: grafana_db
      owner: grafana_admin
      secret:
        name: grafana-db-secret
  storage:
    storageClass: standard
    size: 1Gi
  postgresql:
    parameters:
      # Only log slow queries (e.g., > 250ms) to avoid log flooding
      # log_min_duration_statement: "250"
      log_min_duration_statement: "0"

      log_statement: "none" # Keep this at none if you use min_duration_statement

      # Essential for troubleshooting performance, low volume
      log_checkpoints: "on"
      log_lock_waits: "on"

      # Reduce noise by disabling connection/disconnection logs
      log_connections: "off"
      log_disconnections: "off"

      # Standard logging level (logs errors, fatals, and warnings)
      log_min_messages: "warning"

      # Important for CNPG instance manager
      log_destination: "csvlog"
