---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-db
  namespace: grafana-pg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  bootstrap:
    initdb:
      database: grafana_db
      owner: grafana_admin
      secret:
        name: grafana-db-secret
  storage:
    storageClass: standard
    size: 1Gi
  postgresql:
    parameters:
      # Log queries taking longer than 100ms
      log_min_duration_statement: "0"
      # Log detailed information about the query
      log_checkpoints: "on"
      log_connections: "on"
      log_disconnections: "on"
      log_lock_waits: "on"
      # log_statement: "none"
      # Ensure logs are formatted for easy parsing
      log_destination: "csvlog"
