apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: my-sink-connector
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.kafka.connect.file.FileStreamSinkConnector
  tasksMax: 1
  config:
    file: "/opt/new-output.txt"
    topics: x_topic
