apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-welcome-app
  namespace: argo-cd
  labels:
    app-name: welcome-app
    promoter.argoproj.io/has-promotionstrategy: "true"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  sourceHydrator:
    drySource:
      repoURL: https://github.com/sahil-sharma/k8s-stuff.git
      path: welcome-app-with-gitops-promoter/welcome-app/overlays/prod
      targetRevision: main
    hydrateTo:
      targetBranch: environment/prod-next
    syncSource:
      targetBranch: environment/prod
      path: welcome-app-with-gitops-promoter/welcome-app/overlays/prod
  syncPolicy:
    automated: { prune: true, selfHeal: true, allowEmpty: true }
    syncOptions: [CreateNamespace=true]
