apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  namespace: kafka-cluster
  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.0.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap.kafka-cluster.svc:9092
  groupId: my-connect-group
  configStorageTopic: my-connect-configs
  statusStorageTopic: my-connect-status
  offsetStorageTopic: my-connect-offsets
  template:
    connectContainer:
      env:
        - name: KAFKA_PLUGIN_PATH
          value: "/opt/kafka/plugins"
        - name: OTEL_SERVICE_NAME
          value: "kafka-connect"
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kafka-connect-sso-secret
              key: KAFKA_CONNECT_OIDC_CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kafka-connect-sso-secret
              key: KAFKA_CONNECT_OIDC_CLIENT_SECRET
  tracing:
    type: opentelemetry
  config:
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  authentication:
    type: custom
    sasl: true
    config:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: OAUTHBEARER
      sasl.login.callback.handler.class: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
      sasl.jaas.config: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.token.endpoint.uri="http://sso.local.io:32080/realms/kafka-authz/protocol/openid-connect/token" oauth.client.id="${strimzienv:CLIENT_ID}" oauth.client.secret="${strimzienv:CLIENT_SECRET}";'
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: connect-metrics
        key: metrics-config.yaml
  plugins:
    - name: connector-1
      artifacts:
        - type: image
          reference: sahilwork/test-client:v1
          pullPolicy: Always
