apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-pod-manager
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-pod-manager-binding
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
roleRef:
  kind: Role
  name: vault-pod-manager
  apiGroup: rbac.authorization.k8s.io
