global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  ha:
    enabled: false
    replicas: 1
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          address = "0.0.0.0:8200"
          tls_disable = "true"
          telemetry {
            unauthenticated_metrics_access = "true"
          }
        }
        storage "raft" {
          path    = "/vault/data"
          node_id = "${HOSTNAME}"
        }
        service_registration "kubernetes" {}
        disable_mlock = true

        telemetry {
          prometheus_retention_time = "30s"
          disable_hostname = true
        }
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: "standard"

  ingress:
    enabled: false
    ingressClassName: "nginx"
    pathType: Prefix
    hosts:
      - host: secrets.local.io
        paths:
          - /

  extraEnvironmentVars:
    VAULT_ADDR: http://vault.vault:8200
    VAULT_SKIP_VERIFY: true

serverTelemetry:
  serviceMonitor:
    enabled: true
    selectors:
      release: monitoring
  prometheusRules:
    enabled: true
    selectors:
      release: monitoring
    rules:
      - alert: vault-HighResponseTime
        annotations:
          message: The response time of Vault is over 500ms on average over the last 5 minutes.
        expr: vault_core_handle_request{quantile="0.5", namespace="vault"} > 500
        for: 5m
        labels:
          severity: warning
      - alert: vault-HighResponseTime
        annotations:
          message: The response time of Vault is over 1s on average over the last 5 minutes.
        expr: vault_core_handle_request{quantile="0.5", namespace="vault"} > 1000
        for: 5m
        labels:
          severity: critical
