apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: false

resources:
  - namespace.yaml
  - gateway.yaml
  - virtualservice.yaml
  - dex.yaml

helmCharts:
  - name: litmus
    releaseName: litmus
    namespace: litmus
    repo: https://litmuschaos.github.io/litmus-helm/
    version: 3.28.0
    valuesFile: values.yaml
