apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: staging

replicas:
  - name: welcome-app-deployment
    count: 2

configMapGenerator:
  - name: welcome-app-config
    literals:
      - APP_ENV_NAME="staging"

patches:
  - target:
      kind: VirtualService
      name: welcome-app
    patch: |-
      - op: replace
        path: /spec/hosts/0
        value: staging.welcome.local.io
