apiVersion: v1
data:
  APP_ENV_NAME: staging
  WEBHOOK_TEST_KEY: webhook-triggered-successfully
kind: ConfigMap
metadata:
  name: welcome-app-config
  namespace: staging
---
apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service
  namespace: staging
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: welcome-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: welcome-app
  name: welcome-app-deployment
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: welcome-app-config
          image: bonyscott/welcome-app:working
          name: welcome-app
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: welcome-app
  namespace: staging
spec:
  gateways:
    - argo-cd/welcome-gateway
  hosts:
    - staging.welcome.local.io
  http:
    - route:
        - destination:
            host: welcome-app-service
            port:
              number: 8080
