apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - cluster-issuer.yaml
  # - bundle.yaml

helmCharts:
  - name: trust-manager
    releaseName: trust-manager
    version: v0.22.1
    repo: https://charts.jetstack.io
    includeCRDs: true
    valuesInline:
      app:
        trust:
          namespace: cert-manager
