---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-backup-sa
  namespace: minio
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backup-secret-store
  namespace: minio
spec:
  provider:
    vault:
      server: "http://secrets.local.io:32080"
      path: "apps"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-backup-secret-role"
          serviceAccountRef:
            name: vault-backup-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-backup-external-secret
  namespace: minio
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-backup-secret-store
    kind: SecretStore
  target:
    name: vault-backup-credentials
    creationPolicy: Owner
  data:
    - secretKey: accessKey
      remoteRef:
        key: vault-backup
        property: VAULT_BACKUP_ACCESS_KEY
    - secretKey: secretKey
      remoteRef:
        key: vault-backup
        property: VAULT_BACKUP_SECRET_KEY
