apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: kafka-bridge
  namespace: kafka
spec:
  replicas: 1
  bootstrapServers: my-kafka-cluster-kafka-bootstrap.kafka.svc:9092
  http:
    port: 8080
    cors: 
      allowedOrigins: 
        - ".*"
      allowedMethods: 
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
        - "PATCH"
