apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: service-account-kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "my-kafka-topic"
          patternType: literal
        operations:
          - Read
          - Describe
          - DescribeConfigs
          - Write
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Describe
          - Read
