apiVersion: kafka.strimzi.io/v1
kind: KafkaBridge
metadata:
  name: my-cluster-bridge
  namespace: kafka-cluster
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap.kafka-cluster.svc:9092
  http:
    port: 8080
  authentication:
    type: custom
    sasl: true
    config:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: OAUTHBEARER
      sasl.login.callback.handler.class: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
      sasl.jaas.config: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.token.endpoint.uri="http://sso.local.io:32080/realms/kafka-authz/protocol/openid-connect/token" oauth.client.id="${strimzienv:OAUTH_CLIENT_ID}" oauth.client.secret="${strimzienv:OAUTH_CLIENT_SECRET}";'
  template:
    bridgeContainer:
      env:
        - name: OTEL_SERVICE_NAME
          value: my-cluster-bridge
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        - name: OTEL_TRACES_SAMPLER
          value: "always_on"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector.opentelemetry:4317"
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kafka-bridge-sso-secret
              key: KAFKA_BRIDGE_OIDC_CLIENT_ID
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kafka-bridge-sso-secret
              key: KAFKA_BRIDGE_OIDC_CLIENT_SECRET
  tracing:
    type: opentelemetry
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: bridge-metrics
        key: metrics-config.yaml
---