apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keda

resources:
  - namespace.yaml

helmCharts:
  - name: keda
    includeCRDs: true
    releaseName: keda
    version: 2.19.0
    repo: https://kedacore.github.io/charts
    valuesInline:
      # This tells the Metrics Adapter exactly where to find the Operator
      operator:
        namespace: keda
      # This ensures the Metrics Server itself knows its context
      metricsServer:
        namespace: keda
