apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-cluster-bridge
  namespace: kafka-operator
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap.kafka-operator.svc:9092
  http:
    port: 8080
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: bridge-metrics
        key: metrics-config.yaml
---
